[package]
name = "voicesrv"
version = "0.1.0"
edition = "2021"
publish = false
license = "Zlib"

[workspace]

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
env_logger = "0.11.8"
flate2 = "1.1.9"
futures-util = { version = "0.3", features = ["sink"] }
log = "0.4.27"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.10.9"
tokio = { version = "=1.48.0", features = ["net", "rt-multi-thread", "time", "sync", "macros"] }
warp = { version = "0.3.7", default-features = false, features = ["websocket"] }
